all:
	g++ -g -std=c++11 -o 11.01.exe  11.01.cpp
	g++ -g -std=c++11 -o 13.01.exe  13.01.cpp
	g++ -g -std=c++11 -o 13.02.exe  13.02.cpp
	g++ -g -std=c++11 -o 13.03.exe  13.03.cpp
	g++ -g -std=c++11 -o 13.06.exe  13.06.cpp
	g++ -g -std=c++11 -o graph_client.exe graph_client.cpp

clean:
	rm 11.01.exe 13.01.exe 13.02.exe 13.03.exe 13.06.exe a.out graph_client.exe
